- name: install environment on the docker group machines
  become: true
  hosts: docker
  vars:
    docker_script: install_docker.sh
    kube_script: install_kubernetes.sh

  tasks:
    - name: copy installation scripts on the hosts
      copy: src=./scripts/ dest=/home/ec2-user/scripts/

    - name: change permissions for docker file
      command: chdir=/home/ec2-user/scripts/ chmod a+x {{docker_script}}

    - name: change permissions for kube file
      command: chdir=/home/ec2-user/scripts/ chmod a+x {{kube_script}}

    - name: run docker installation script
      command: chdir=/home/ec2-user/scripts/ ./{{docker_script}}

    - name: run kubernetes installation script
      command: chdir=/home/ec2-user/scripts/ ./{{kube_script}}
    
    - name: copy hosts file
      copy: src=./files/hosts dest=/etc/hosts 
    
- name: copy key file and install network plugin
  become: true
  hosts: master
  tasks:
    - name: copy key file
      copy: src=./.ssh/aprylypaKey.pem dest=/home/ec2-user/.ssh/aprylypaKey.pem
    - name: install network plugin
      command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"