- name: join workers
  become: true
  hosts: worker
  tasks:
    - name: copy script
      copy: src=./files/join_.sh dest=/home/ec2-user/join_.sh owner=ec2-user mode=0700
 
    - name: run script
      shell: /home/ec2-user/join_.sh